#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR='mvim -f --nomru -c "au VimLeave * !open -a iTerm"'
export SVN_EDITOR='mvim -f --nomru -c "au VimLeave * !open -a iTerm"'

